model: o4-mini
approvalMode: full-auto
fullAutoErrorMode: ask-user
notify: true

ignorePaths:
  - Build_docs/bib_entries/**
  - Build_docs/bib_files/**
  - Build_docs/audio_files/*.wav

prompts:
  DraftBuildDocsReadme:
    description: "Draft Build_docs/README.md explaining the Sphinx documentation build workflow"
    prompt: |
      You are an assistant that writes clear, detailed README documentation for a Sphinx-based project.
      Given the `Build_docs/` directory of the SPDEs-Bib repository, generate a `README.md` that:
      - Provides an overview of the directory layout and purpose of each folder.
      - Explains key scripts (`Bibtexparser-all.py`, `add_podcast.py`, `script.sh`), including their main functions.
      - Describes the Sphinx configuration in `conf.py`, including extensions and hooks such as `run_add_podcast`.
      - Details build commands (`make html`, `make linkcheck`, Windows `make.bat`) and dependencies.
      - Covers deployment steps (Makefile `deploy` target, GitHub Pages, Read the Docs integration).
      - Maintains clarity, readability, and proper Markdown formatting.
      Output the complete Markdown content for `Build_docs/README.md`.
