name: Compile All.tex LaTeX Document
on:
  push:
    branches:
      - main  # Or any specific branch you want

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

    - name: Compile LaTeX document
      run: |
        lualatex All.tex || exit 1
        biber All || exit 1
        lualatex All.tex || exit 1
        lualatex All.tex || exit 1

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: Compiled-PDF
        path: ./All.pdf
